### ISSUE TITLE
Develop contingency plans for potential network problems during SyncSlides demo

### ISSUE THREAD

**Issue by jwnichls** [vanadium-archive/java#1]
Certainly this should include the option of bringing our own access point and perhaps a battery-powered access point should we have power issues.

**Comment by asimshankar** [comment]
This is the set of things I'm researching:
- Battery powered access point (i.e., a wireless network possibly not connected to the internet)
- Possibly wired ethernet connections for tablets/phones
- Portable hotspot (for internet connectivity)

A couple of questions for @kenashcraft @monopole @jwnichls 
- Internet connectivity is _not_ required to make the demo work, correct? Is a set of N devices that we bring, with the .apk preinstalled on them and connected to our own wireless network without internet connectivity a viable fallback setup?
- What is the set of devices that we will be using? How many phones, which ones - Nexus 5/MotoX/something else? Is there a tablet involved? A laptop/Pi?

**Comment by kenashcraft** [comment]
Correct, internet connectivity is not required, and our primary plan is to
not use the internet.

The set of devices has not been discussed in detail, but it needs to be.
It would help in our UI development if we could focus on one phone model
and one tablet model.  Perhaps we already have these devices floating
around the team.  The only concrete requirement is that they must run
Android L.

**Comment by asimshankar** [comment]
Setup described in https://docs.google.com/document/d/10-aqphmPwL1eDXzW6X29Ey42CFmOnaBaPB0PCjPwcH4/edit#

I do not have plans to do anything further unless someone tells me to, so I'm closing this issue.

The only requirement a single power outlet.
